import { access, mkdir, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'

import type { Command } from 'commander'

import { c, configureColor } from '../lib/colors.js'
import { EXIT_OK, EXIT_USAGE } from '../lib/exit-codes.js'

type CiOptions = {
  strict?: boolean
  force?: boolean
  cwd?: string
  color?: boolean
}

type Provider = 'github' | 'gitlab' | 'circle'

function githubWorkflow(strict: boolean): string {
  const checkLine = strict
    ? '          npx -y driftlog@^1 check --strict'
    : '          npx -y driftlog@^1 check'
  return `# Generated by driftlog ci github. Idempotent -- rerunning regenerates this file.
name: Driftlog

on:
  pull_request:
  push:
    branches: [main]

jobs:
  drift:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run Driftlog
        run: |
${checkLine}
`
}

function gitlabSnippet(strict: boolean): string {
  const checkLine = strict
    ? '    - npx -y driftlog@^1 check --strict'
    : '    - npx -y driftlog@^1 check'
  return `# Generated by driftlog ci gitlab. Include this file from your .gitlab-ci.yml
# via:   include: '.driftlog-gitlab-ci.yml'

driftlog:
  image: node:20
  stage: test
  script:
${checkLine}
`
}

function circleSnippet(strict: boolean): string {
  const checkLine = strict
    ? '            npx -y driftlog@^1 check --strict'
    : '            npx -y driftlog@^1 check'
  return `# Generated by driftlog ci circle. Include this file from your .circleci/config.yml
# via the orb / job composition for your project.

version: 2.1
jobs:
  driftlog:
    docker:
      - image: cimg/node:20.0
    steps:
      - checkout
      - run:
          name: Run Driftlog
          command: |
${checkLine}
workflows:
  drift:
    jobs:
      - driftlog
`
}

const TARGETS: Record<Provider, { path: string; render: (s: boolean) => string }> = {
  github: { path: '.github/workflows/driftlog.yml', render: githubWorkflow },
  gitlab: { path: '.driftlog-gitlab-ci.yml', render: gitlabSnippet },
  circle: { path: '.circleci/driftlog.yml', render: circleSnippet },
}

async function fileExists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

async function writeProvider(
  provider: Provider,
  options: CiOptions,
): Promise<void> {
  const cwd = options.cwd ? resolve(options.cwd) : process.cwd()
  const target = resolve(cwd, TARGETS[provider].path)

  if ((await fileExists(target)) && !options.force) {
    process.stderr.write(
      `driftlog: ${TARGETS[provider].path} already exists. Use --force to overwrite.\n`,
    )
    process.exit(EXIT_USAGE)
  }

  await mkdir(dirname(target), { recursive: true })
  await writeFile(target, TARGETS[provider].render(options.strict ?? false), 'utf8')

  process.stdout.write(`Wrote ${c.bold(TARGETS[provider].path)}\n`)
  if (provider === 'gitlab') {
    process.stdout.write(
      c.dim(
        `Add this to your .gitlab-ci.yml:\n  include: '${TARGETS[provider].path}'\n`,
      ),
    )
  }
  if (provider === 'circle') {
    process.stdout.write(
      c.dim(
        `Include this in your .circleci/config.yml workflows or replace your config with it.\n`,
      ),
    )
  }
}

export function registerCi(program: Command): void {
  const ci = program
    .command('ci')
    .description('Generate a CI config tailored to your provider.')

  ci.command('github')
    .description('Write .github/workflows/driftlog.yml.')
    .option('--strict', 'Pass --strict to driftlog check in the generated job.')
    .option('--force', 'Overwrite the existing workflow file.')
    .option('--cwd <dir>', 'Working directory.')
    .option('--no-color', 'Disable ANSI colour.')
    .action(async (options: CiOptions) => {
      configureColor(options.color === false ? false : 'auto')
      await writeProvider('github', options)
      process.exit(EXIT_OK)
    })

  ci.command('gitlab')
    .description('Write .driftlog-gitlab-ci.yml (include from your existing pipeline).')
    .option('--strict', 'Pass --strict to driftlog check in the generated job.')
    .option('--force', 'Overwrite the existing file.')
    .option('--cwd <dir>', 'Working directory.')
    .option('--no-color', 'Disable ANSI colour.')
    .action(async (options: CiOptions) => {
      configureColor(options.color === false ? false : 'auto')
      await writeProvider('gitlab', options)
      process.exit(EXIT_OK)
    })

  ci.command('circle')
    .description('Write .circleci/driftlog.yml.')
    .option('--strict', 'Pass --strict to driftlog check in the generated job.')
    .option('--force', 'Overwrite the existing file.')
    .option('--cwd <dir>', 'Working directory.')
    .option('--no-color', 'Disable ANSI colour.')
    .action(async (options: CiOptions) => {
      configureColor(options.color === false ? false : 'auto')
      await writeProvider('circle', options)
      process.exit(EXIT_OK)
    })
}
